### ISSUE TITLE
The version uploaded to PyPI does not support Python 3

### ISSUE THREAD

**Issue by mugwort-rc** [rainwoodman/chealpy#1]
https://pypi.org/project/chealpy/

Could you please upload current version it if possible?

(I know that I can get the latest version in by running the `pip install git+https://github.com/rainwoodman/chealpy`...)

**Comment by rainwoodman** [comment]
I cut a 0.1.1 release and uploaded it to pypi.

Would you see if it works?

**Comment by rainwoodman** [comment]
The master is now built and tested for py3 on travis, and automatic deployment is added. Marking as fixed.
